services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: water-wiki-api
    volumes:
      - ./backend:/app
    environment:
        - TZ=Asia/Seoul
        - APP_MODE=prod

  nginx:
    image: nginx:stable-alpine
    container_name: water-wiki-nginx
    restart: always
    depends_on:
      - api
    volumes:
      - ./frontend/dist:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      # - 443:443
      - 80:80
    environment:
        - TZ=Asia/Seoul
