"""empty message

Revision ID: 430f337bf358
Revises: b2bcf8ac5811
Create Date: 2023-08-11 18:56:06.713389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "430f337bf358"
down_revision = "b2bcf8ac5811"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("supplier", sa.Column("loc_x", sa.Float(), nullable=True))
    op.add_column("supplier", sa.Column("loc_y", sa.Float(), nullable=True))
    op.add_column("vendor", sa.Column("loc_x", sa.Float(), nullable=True))
    op.add_column("vendor", sa.Column("loc_y", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor", "loc_y")
    op.drop_column("vendor", "loc_x")
    op.drop_column("supplier", "loc_y")
    op.drop_column("supplier", "loc_x")
    # ### end Alembic commands ###
