"""empty message

Revision ID: 71c4a8c591a9
Revises: 5dad11b29eae
Create Date: 2023-08-10 19:57:56.491266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71c4a8c591a9"
down_revision = "5dad11b29eae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "violation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issued_datetime", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=True),
        sa.Column("end_datetime", sa.DateTime(), nullable=True),
        sa.Column("detail", sa.String(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("violation")
    # ### end Alembic commands ###
