"""empty message

Revision ID: b2bcf8ac5811
Revises: 71c4a8c591a9
Create Date: 2023-08-10 22:51:36.672646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2bcf8ac5811"
down_revision = "71c4a8c591a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("violation", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("violation", "title")
    # ### end Alembic commands ###
